services:
  mongodb:
    image: mongo:latest
    container_name: authentication_app_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: authentication_app
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth_network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: authentication_app_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - auth_network

  backend:
    build:
      context: ./nestjs-server
      dockerfile: Dockerfile
    container_name: nestjs-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/authentication_app
      - JWT_EXPIRES_IN=7d
      - DATABASE_NAME=authentication_app
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./nestjs-server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
        - auth_network
  frontend:
    build:
      context: ./reactjs-client
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./reactjs-client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
    - auth_network

volumes:
  mongodb_data:

networks:
  auth_network:
    driver: bridge